version: '3.0'
services:
  db:
    image: mysql
    volumes:
      - "./.data/db:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    ports:
      - 42333:3306
  rasa:
    image: rasa/rasa:3.2.2-full
    volumes:
      - ./:/app
    command:
      - run
    expose: 
      - 5005
    ports:
      - 5005:5005